# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c694fbe710a7ce7b9904c2085ba5b6da6657c1a779b77c38b97ab272dcb002dd90637e02820804f39da4291156e1dbad978a5611ac3355248228d622b5aaea7

test:
  secret_key_base: bcedd69b5ebeac9da38de3ff946d6f25dfb9b8f5af3ba4a25f259cd94580564ef87279966d20bd7b9e04fbbfaec9926e2335cec2c63f1faa8206f6c2d38b11df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
